// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: daoncore/contentregistry/v1/content_record.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "daoncore.contentregistry.v1";

/** ContentRecord defines the ContentRecord message. */
export interface ContentRecord {
  contentHash: string;
  creator: string;
  license: string;
  timestamp: number;
  platform: string;
  fingerprint: string;
  revisionHistory: string[];
  transferHistory: string[];
}

function createBaseContentRecord(): ContentRecord {
  return {
    contentHash: "",
    creator: "",
    license: "",
    timestamp: 0,
    platform: "",
    fingerprint: "",
    revisionHistory: [],
    transferHistory: [],
  };
}

export const ContentRecord: MessageFns<ContentRecord> = {
  encode(message: ContentRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contentHash !== "") {
      writer.uint32(10).string(message.contentHash);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    if (message.license !== "") {
      writer.uint32(26).string(message.license);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    if (message.platform !== "") {
      writer.uint32(42).string(message.platform);
    }
    if (message.fingerprint !== "") {
      writer.uint32(50).string(message.fingerprint);
    }
    for (const v of message.revisionHistory) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.transferHistory) {
      writer.uint32(66).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContentRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContentRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.license = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fingerprint = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.revisionHistory.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.transferHistory.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContentRecord {
    return {
      contentHash: isSet(object.contentHash) ? globalThis.String(object.contentHash) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      license: isSet(object.license) ? globalThis.String(object.license) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      fingerprint: isSet(object.fingerprint) ? globalThis.String(object.fingerprint) : "",
      revisionHistory: globalThis.Array.isArray(object?.revisionHistory)
        ? object.revisionHistory.map((e: any) => globalThis.String(e))
        : [],
      transferHistory: globalThis.Array.isArray(object?.transferHistory)
        ? object.transferHistory.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ContentRecord): unknown {
    const obj: any = {};
    if (message.contentHash !== "") {
      obj.contentHash = message.contentHash;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.license !== "") {
      obj.license = message.license;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.fingerprint !== "") {
      obj.fingerprint = message.fingerprint;
    }
    if (message.revisionHistory?.length) {
      obj.revisionHistory = message.revisionHistory;
    }
    if (message.transferHistory?.length) {
      obj.transferHistory = message.transferHistory;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContentRecord>, I>>(base?: I): ContentRecord {
    return ContentRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContentRecord>, I>>(object: I): ContentRecord {
    const message = createBaseContentRecord();
    message.contentHash = object.contentHash ?? "";
    message.creator = object.creator ?? "";
    message.license = object.license ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.platform = object.platform ?? "";
    message.fingerprint = object.fingerprint ?? "";
    message.revisionHistory = object.revisionHistory?.map((e) => e) || [];
    message.transferHistory = object.transferHistory?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
