// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: daoncore/contentregistry/v1/content_record.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ContentRecord defines the ContentRecord message.
type ContentRecord struct {
	ContentHash     string   `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Creator         string   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	License         string   `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	Timestamp       int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Platform        string   `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Fingerprint     string   `protobuf:"bytes,6,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	RevisionHistory []string `protobuf:"bytes,7,rep,name=revision_history,json=revisionHistory,proto3" json:"revision_history,omitempty"`
	TransferHistory []string `protobuf:"bytes,8,rep,name=transfer_history,json=transferHistory,proto3" json:"transfer_history,omitempty"`
}

func (m *ContentRecord) Reset()         { *m = ContentRecord{} }
func (m *ContentRecord) String() string { return proto.CompactTextString(m) }
func (*ContentRecord) ProtoMessage()    {}
func (*ContentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_28508e1c186ad23d, []int{0}
}
func (m *ContentRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContentRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentRecord.Merge(m, src)
}
func (m *ContentRecord) XXX_Size() int {
	return m.Size()
}
func (m *ContentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ContentRecord proto.InternalMessageInfo

func (m *ContentRecord) GetContentHash() string {
	if m != nil {
		return m.ContentHash
	}
	return ""
}

func (m *ContentRecord) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ContentRecord) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *ContentRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ContentRecord) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ContentRecord) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *ContentRecord) GetRevisionHistory() []string {
	if m != nil {
		return m.RevisionHistory
	}
	return nil
}

func (m *ContentRecord) GetTransferHistory() []string {
	if m != nil {
		return m.TransferHistory
	}
	return nil
}

func init() {
	proto.RegisterType((*ContentRecord)(nil), "daoncore.contentregistry.v1.ContentRecord")
}

func init() {
	proto.RegisterFile("daoncore/contentregistry/v1/content_record.proto", fileDescriptor_28508e1c186ad23d)
}

var fileDescriptor_28508e1c186ad23d = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbd, 0x4e, 0x02, 0x41,
	0x14, 0x85, 0x59, 0x50, 0x7e, 0x06, 0x8d, 0x66, 0xaa, 0x89, 0x9a, 0xcd, 0x6a, 0x85, 0x85, 0x8b,
	0xc4, 0xca, 0x56, 0x1b, 0xea, 0xb5, 0xb3, 0x21, 0xc3, 0x72, 0x61, 0x27, 0xb2, 0x73, 0x37, 0x77,
	0xae, 0x28, 0x6f, 0x61, 0xe9, 0x23, 0x59, 0x52, 0x5a, 0x1a, 0x78, 0x11, 0xc3, 0xfe, 0xa0, 0xd1,
	0xf2, 0x7c, 0xe7, 0x9c, 0xc9, 0xe4, 0x1e, 0x71, 0x3d, 0xd1, 0x68, 0x63, 0x24, 0xe8, 0xc7, 0x68,
	0x19, 0x2c, 0x13, 0xcc, 0x8c, 0x63, 0x5a, 0xf6, 0x17, 0x83, 0x0a, 0x8d, 0x08, 0x62, 0xa4, 0x49,
	0x98, 0x11, 0x32, 0xca, 0xd3, 0xaa, 0x11, 0xfe, 0x69, 0x84, 0x8b, 0xc1, 0xc5, 0x7b, 0x5d, 0x1c,
	0xde, 0x17, 0x38, 0xca, 0x4b, 0xf2, 0x5c, 0x1c, 0x54, 0xcf, 0x24, 0xda, 0x25, 0xca, 0x0b, 0xbc,
	0x5e, 0x27, 0xea, 0x96, 0x6c, 0xa8, 0x5d, 0x22, 0x95, 0x68, 0xc5, 0x04, 0x9a, 0x91, 0x54, 0x3d,
	0x77, 0x2b, 0xb9, 0x75, 0xe6, 0x26, 0x06, 0xeb, 0x40, 0x35, 0x0a, 0xa7, 0x94, 0xf2, 0x4c, 0x74,
	0xd8, 0xa4, 0xe0, 0x58, 0xa7, 0x99, 0xda, 0x0b, 0xbc, 0x5e, 0x23, 0xfa, 0x01, 0xf2, 0x44, 0xb4,
	0xb3, 0xb9, 0xe6, 0x29, 0x52, 0xaa, 0xf6, 0xf3, 0xe2, 0x4e, 0xcb, 0x40, 0x74, 0xa7, 0xc6, 0xce,
	0x80, 0x32, 0x32, 0x96, 0x55, 0xb3, 0xf8, 0xcf, 0x2f, 0x24, 0x2f, 0xc5, 0x31, 0xc1, 0xc2, 0x38,
	0x83, 0x76, 0x94, 0x18, 0xc7, 0x48, 0x4b, 0xd5, 0x0a, 0x1a, 0xbd, 0x4e, 0x74, 0x54, 0xf1, 0x61,
	0x81, 0xb7, 0x51, 0x26, 0x6d, 0xdd, 0x14, 0x68, 0x17, 0x6d, 0x17, 0xd1, 0x8a, 0x97, 0xd1, 0xbb,
	0x87, 0x8f, 0xb5, 0xef, 0xad, 0xd6, 0xbe, 0xf7, 0xb5, 0xf6, 0xbd, 0xb7, 0x8d, 0x5f, 0x5b, 0x6d,
	0xfc, 0xda, 0xe7, 0xc6, 0xaf, 0x3d, 0xde, 0xce, 0x0c, 0x27, 0xcf, 0xe3, 0x30, 0xc6, 0xb4, 0xbf,
	0x3d, 0xee, 0x95, 0x05, 0x7e, 0x41, 0x7a, 0x2a, 0x44, 0x3e, 0xce, 0xeb, 0xbf, 0x79, 0x78, 0x99,
	0x81, 0x1b, 0x37, 0xf3, 0x4d, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xcf, 0x36, 0x37,
	0xc7, 0x01, 0x00, 0x00,
}

func (m *ContentRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContentRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContentRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TransferHistory) > 0 {
		for iNdEx := len(m.TransferHistory) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TransferHistory[iNdEx])
			copy(dAtA[i:], m.TransferHistory[iNdEx])
			i = encodeVarintContentRecord(dAtA, i, uint64(len(m.TransferHistory[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.RevisionHistory) > 0 {
		for iNdEx := len(m.RevisionHistory) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RevisionHistory[iNdEx])
			copy(dAtA[i:], m.RevisionHistory[iNdEx])
			i = encodeVarintContentRecord(dAtA, i, uint64(len(m.RevisionHistory[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Fingerprint) > 0 {
		i -= len(m.Fingerprint)
		copy(dAtA[i:], m.Fingerprint)
		i = encodeVarintContentRecord(dAtA, i, uint64(len(m.Fingerprint)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Platform) > 0 {
		i -= len(m.Platform)
		copy(dAtA[i:], m.Platform)
		i = encodeVarintContentRecord(dAtA, i, uint64(len(m.Platform)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Timestamp != 0 {
		i = encodeVarintContentRecord(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.License) > 0 {
		i -= len(m.License)
		copy(dAtA[i:], m.License)
		i = encodeVarintContentRecord(dAtA, i, uint64(len(m.License)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintContentRecord(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintContentRecord(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContentRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovContentRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ContentRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovContentRecord(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovContentRecord(uint64(l))
	}
	l = len(m.License)
	if l > 0 {
		n += 1 + l + sovContentRecord(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovContentRecord(uint64(m.Timestamp))
	}
	l = len(m.Platform)
	if l > 0 {
		n += 1 + l + sovContentRecord(uint64(l))
	}
	l = len(m.Fingerprint)
	if l > 0 {
		n += 1 + l + sovContentRecord(uint64(l))
	}
	if len(m.RevisionHistory) > 0 {
		for _, s := range m.RevisionHistory {
			l = len(s)
			n += 1 + l + sovContentRecord(uint64(l))
		}
	}
	if len(m.TransferHistory) > 0 {
		for _, s := range m.TransferHistory {
			l = len(s)
			n += 1 + l + sovContentRecord(uint64(l))
		}
	}
	return n
}

func sovContentRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContentRecord(x uint64) (n int) {
	return sovContentRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContentRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContentRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContentRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContentRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field License", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.License = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Platform", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Platform = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fingerprint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fingerprint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionHistory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevisionHistory = append(m.RevisionHistory, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferHistory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransferHistory = append(m.TransferHistory, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContentRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContentRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContentRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContentRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContentRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContentRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContentRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContentRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContentRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContentRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContentRecord = fmt.Errorf("proto: unexpected end of group")
)
