// GENERATED by scripts/build-icon-sprite.mjs -- do not edit by hand.
// Icon geometry from lucide-react, the same package the frontend imports.
// Run `node scripts/build-icon-sprite.mjs` to regenerate.

const DAON_ICONS = {
  "bot": [
    [
      "path",
      {
        "d": "M12 8V4H8",
        "key": "hb8ula"
      }
    ],
    [
      "rect",
      {
        "width": "16",
        "height": "12",
        "x": "4",
        "y": "8",
        "rx": "2",
        "key": "enze0r"
      }
    ],
    [
      "path",
      {
        "d": "M2 14h2",
        "key": "vft8re"
      }
    ],
    [
      "path",
      {
        "d": "M20 14h2",
        "key": "4cs60a"
      }
    ],
    [
      "path",
      {
        "d": "M15 13v2",
        "key": "1xurst"
      }
    ],
    [
      "path",
      {
        "d": "M9 13v2",
        "key": "rq6x2g"
      }
    ]
  ],
  "check": [
    [
      "path",
      {
        "d": "M20 6 9 17l-5-5",
        "key": "1gmf2c"
      }
    ]
  ],
  "circle": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
        "key": "1mglay"
      }
    ]
  ],
  "circle-check": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
        "key": "1mglay"
      }
    ],
    [
      "path",
      {
        "d": "m9 12 2 2 4-4",
        "key": "dzmm74"
      }
    ]
  ],
  "circle-x": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
        "key": "1mglay"
      }
    ],
    [
      "path",
      {
        "d": "m15 9-6 6",
        "key": "1uzhvr"
      }
    ],
    [
      "path",
      {
        "d": "m9 9 6 6",
        "key": "z0biqf"
      }
    ]
  ],
  "clipboard": [
    [
      "rect",
      {
        "width": "8",
        "height": "4",
        "x": "8",
        "y": "2",
        "rx": "1",
        "ry": "1",
        "key": "tgr4d6"
      }
    ],
    [
      "path",
      {
        "d": "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2",
        "key": "116196"
      }
    ]
  ],
  "coffee": [
    [
      "path",
      {
        "d": "M10 2v2",
        "key": "7u0qdc"
      }
    ],
    [
      "path",
      {
        "d": "M14 2v2",
        "key": "6buw04"
      }
    ],
    [
      "path",
      {
        "d": "M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1",
        "key": "pwadti"
      }
    ],
    [
      "path",
      {
        "d": "M6 2v2",
        "key": "colzsn"
      }
    ]
  ],
  "file-pen": [
    [
      "path",
      {
        "d": "M12.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v9.34",
        "key": "o6klzx"
      }
    ],
    [
      "path",
      {
        "d": "M14 2v5a1 1 0 0 0 1 1h5",
        "key": "wfsgrz"
      }
    ],
    [
      "path",
      {
        "d": "M10.378 12.622a1 1 0 0 1 3 3.003L8.36 20.637a2 2 0 0 1-.854.506l-2.867.837a.5.5 0 0 1-.62-.62l.836-2.869a2 2 0 0 1 .506-.853z",
        "key": "zhnas1"
      }
    ]
  ],
  "globe": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
        "key": "1mglay"
      }
    ],
    [
      "path",
      {
        "d": "M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20",
        "key": "13o1zl"
      }
    ],
    [
      "path",
      {
        "d": "M2 12h20",
        "key": "9i4pu4"
      }
    ]
  ],
  "key-round": [
    [
      "path",
      {
        "d": "M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z",
        "key": "1s6t7t"
      }
    ],
    [
      "circle",
      {
        "cx": "16.5",
        "cy": "7.5",
        "r": ".5",
        "fill": "currentColor",
        "key": "w0ekpg"
      }
    ]
  ],
  "laptop": [
    [
      "path",
      {
        "d": "M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z",
        "key": "1pdavp"
      }
    ],
    [
      "path",
      {
        "d": "M20.054 15.987H3.946",
        "key": "14rxg9"
      }
    ]
  ],
  "lightbulb": [
    [
      "path",
      {
        "d": "M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5",
        "key": "1gvzjb"
      }
    ],
    [
      "path",
      {
        "d": "M9 18h6",
        "key": "x1upvd"
      }
    ],
    [
      "path",
      {
        "d": "M10 22h4",
        "key": "ceow96"
      }
    ]
  ],
  "link": [
    [
      "path",
      {
        "d": "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71",
        "key": "1cjeqo"
      }
    ],
    [
      "path",
      {
        "d": "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71",
        "key": "19qd67"
      }
    ]
  ],
  "lock": [
    [
      "rect",
      {
        "width": "18",
        "height": "11",
        "x": "3",
        "y": "11",
        "rx": "2",
        "ry": "2",
        "key": "1w4ew1"
      }
    ],
    [
      "path",
      {
        "d": "M7 11V7a5 5 0 0 1 10 0v4",
        "key": "fwvmzm"
      }
    ]
  ],
  "lock-keyhole": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "16",
        "r": "1",
        "key": "1au0dj"
      }
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "10",
        "width": "18",
        "height": "12",
        "rx": "2",
        "key": "6s8ecr"
      }
    ],
    [
      "path",
      {
        "d": "M7 10V7a5 5 0 0 1 10 0v3",
        "key": "1pqi11"
      }
    ]
  ],
  "mail": [
    [
      "path",
      {
        "d": "m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7",
        "key": "132q7q"
      }
    ],
    [
      "rect",
      {
        "x": "2",
        "y": "4",
        "width": "20",
        "height": "16",
        "rx": "2",
        "key": "izxlao"
      }
    ]
  ],
  "party-popper": [
    [
      "path",
      {
        "d": "M5.8 11.3 2 22l10.7-3.79",
        "key": "gwxi1d"
      }
    ],
    [
      "path",
      {
        "d": "M4 3h.01",
        "key": "1vcuye"
      }
    ],
    [
      "path",
      {
        "d": "M22 8h.01",
        "key": "1mrtc2"
      }
    ],
    [
      "path",
      {
        "d": "M15 2h.01",
        "key": "1cjtqr"
      }
    ],
    [
      "path",
      {
        "d": "M22 20h.01",
        "key": "1mrys2"
      }
    ],
    [
      "path",
      {
        "d": "m22 2-2.24.75a2.9 2.9 0 0 0-1.96 3.12c.1.86-.57 1.63-1.45 1.63h-.38c-.86 0-1.6.6-1.76 1.44L14 10",
        "key": "hbicv8"
      }
    ],
    [
      "path",
      {
        "d": "m22 13-.82-.33c-.86-.34-1.82.2-1.98 1.11c-.11.7-.72 1.22-1.43 1.22H17",
        "key": "1i94pl"
      }
    ],
    [
      "path",
      {
        "d": "m11 2 .33.82c.34.86-.2 1.82-1.11 1.98C9.52 4.9 9 5.52 9 6.23V7",
        "key": "1cofks"
      }
    ],
    [
      "path",
      {
        "d": "M11 13c1.93 1.93 2.83 4.17 2 5-.83.83-3.07-.07-5-2-1.93-1.93-2.83-4.17-2-5 .83-.83 3.07.07 5 2Z",
        "key": "4kbmks"
      }
    ]
  ],
  "refresh-cw": [
    [
      "path",
      {
        "d": "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
        "key": "v9h5vc"
      }
    ],
    [
      "path",
      {
        "d": "M21 3v5h-5",
        "key": "1q7to0"
      }
    ],
    [
      "path",
      {
        "d": "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
        "key": "3uifl3"
      }
    ],
    [
      "path",
      {
        "d": "M8 16H3v5",
        "key": "1cv678"
      }
    ]
  ],
  "satellite-dish": [
    [
      "path",
      {
        "d": "M4 10a7.31 7.31 0 0 0 10 10Z",
        "key": "1fzpp3"
      }
    ],
    [
      "path",
      {
        "d": "m9 15 3-3",
        "key": "88sc13"
      }
    ],
    [
      "path",
      {
        "d": "M17 13a6 6 0 0 0-6-6",
        "key": "15cc6u"
      }
    ],
    [
      "path",
      {
        "d": "M21 13A10 10 0 0 0 11 3",
        "key": "11nf8s"
      }
    ]
  ],
  "save": [
    [
      "path",
      {
        "d": "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z",
        "key": "1c8476"
      }
    ],
    [
      "path",
      {
        "d": "M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7",
        "key": "1ydtos"
      }
    ],
    [
      "path",
      {
        "d": "M7 3v4a1 1 0 0 0 1 1h7",
        "key": "t51u73"
      }
    ]
  ],
  "scale": [
    [
      "path",
      {
        "d": "M12 3v18",
        "key": "108xh3"
      }
    ],
    [
      "path",
      {
        "d": "m19 8 3 8a5 5 0 0 1-6 0zV7",
        "key": "zcdpyk"
      }
    ],
    [
      "path",
      {
        "d": "M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1",
        "key": "1yorad"
      }
    ],
    [
      "path",
      {
        "d": "m5 8 3 8a5 5 0 0 1-6 0zV7",
        "key": "eua70x"
      }
    ],
    [
      "path",
      {
        "d": "M7 21h10",
        "key": "1b0cd5"
      }
    ]
  ],
  "search": [
    [
      "path",
      {
        "d": "m21 21-4.34-4.34",
        "key": "14j7rj"
      }
    ],
    [
      "circle",
      {
        "cx": "11",
        "cy": "11",
        "r": "8",
        "key": "4ej97u"
      }
    ]
  ],
  "shield": [
    [
      "path",
      {
        "d": "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
        "key": "oel41y"
      }
    ]
  ],
  "smartphone": [
    [
      "rect",
      {
        "width": "14",
        "height": "20",
        "x": "5",
        "y": "2",
        "rx": "2",
        "ry": "2",
        "key": "1yt0o3"
      }
    ],
    [
      "path",
      {
        "d": "M12 18h.01",
        "key": "mhygvu"
      }
    ]
  ],
  "target": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
        "key": "1mglay"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "6",
        "key": "1vlfrh"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "2",
        "key": "1c9p78"
      }
    ]
  ],
  "triangle-alert": [
    [
      "path",
      {
        "d": "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
        "key": "wmoenq"
      }
    ],
    [
      "path",
      {
        "d": "M12 9v4",
        "key": "juzpu7"
      }
    ],
    [
      "path",
      {
        "d": "M12 17h.01",
        "key": "p32p05"
      }
    ]
  ],
  "x": [
    [
      "path",
      {
        "d": "M18 6 6 18",
        "key": "1bl5f8"
      }
    ],
    [
      "path",
      {
        "d": "m6 6 12 12",
        "key": "d8bk6v"
      }
    ]
  ],
  "zap": [
    [
      "path",
      {
        "d": "M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z",
        "key": "1v7up4"
      }
    ]
  ]
};

const DAON_SVG_NS = 'http://www.w3.org/2000/svg';

/**
 * Build an icon as real DOM nodes.
 *
 * Returns an element rather than a markup string so callers can drop an icon
 * beside text without reaching for innerHTML, which would turn any interpolated
 * value into an injection risk.
 */
function daonIcon(name, size = 16) {
  const node = DAON_ICONS[name];
  if (!node) throw new Error('unknown icon: ' + name);
  const svg = document.createElementNS(DAON_SVG_NS, 'svg');
  for (const [k, v] of Object.entries({
    width: size, height: size, viewBox: '0 0 24 24', fill: 'none',
    stroke: 'currentColor', 'stroke-width': '2',
    'stroke-linecap': 'round', 'stroke-linejoin': 'round',
    'aria-hidden': 'true',
  })) svg.setAttribute(k, String(v));
  svg.style.verticalAlign = '-0.125em';
  svg.style.flex = 'none';
  for (const [tag, attrs] of node) {
    const el = document.createElementNS(DAON_SVG_NS, tag);
    for (const [k, v] of Object.entries(attrs)) if (k !== 'key') el.setAttribute(k, String(v));
    svg.appendChild(el);
  }
  return svg;
}

/**
 * Replace an element's contents with an icon followed by text.
 * Text goes in via a text node, so it is never parsed as markup.
 */
function daonSetStatus(el, iconName, text, size = 16) {
  el.replaceChildren(daonIcon(iconName, size), document.createTextNode(' ' + text));
}

/** Trusted markup string, for the few places already building an HTML template. */
function daonIconMarkup(name, size = 16) {
  const node = DAON_ICONS[name];
  if (!node) throw new Error('unknown icon: ' + name);
  const body = node
    .map(([tag, attrs]) =>
      '<' + tag + ' ' + Object.entries(attrs).filter(([k]) => k !== 'key')
        .map(([k, v]) => k + '="' + String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;') + '"')
        .join(' ') + '/>')
    .join('');
  return '<svg xmlns="' + DAON_SVG_NS + '" width="' + size + '" height="' + size +
    '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
    'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" ' +
    'style="vertical-align:-0.125em">' + body + '</svg>';
}
